# action to check whether scheduled jobs still run
name: Debug Action

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Debug Command
        run: echo "This is a debug message"
